name: frog_jwt
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev.11
  dart_jsonwebtoken: ^2.4.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^3.0.1
