name: dart_server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.0.1-dev
  dart_jsonwebtoken: ^2.4.2
  frog_jwt:
    path: ../packages/frog_jwt
  pg_user_api:
    path: ../packages/pg_user_api
  postgres: ^2.4.6
  user_repository:
    path: ../packages/user_repository

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
